### ISSUE TITLE
Question regarding a job/bounty

### ISSUE THREAD

**Issue by IPv6** [skial/haxe.io#1043]
Willing to put a bounty to properly fix this longstanding issue in hxcpp - https://github.com/HaxeFoundation/hxcpp/issues/1019 - in hxcpp master.  Need an actual commit to hxcpp project in the end (so everyone will benefit of this fix), not a local patch. But it is really hard to tell how much the price should be... Are there any rules on this? Any suggestions/possible alternatives are welcome too.

Sorry if this is not a right place to ask such questions //

**Comment by skial** [comment]
Hey @IPv6, sorry for the slow reply.

I'd expect you would get much better visibility and answers over on https://community.haxe.org/, if you haven't already asked.

From a quick search through this repo for bounties and cpp it appears 250-400 dollars might be a baseline starting price 🤷.

I've included this question in the latest roundup in case anyone has better advice for you or is interested in fixing it.

**Comment by IPv6** [comment]
@skial thank you very much! will wait for possible reaction after roundup and move to https://community.haxe.org/ for further search.

this longstanding issue need to be fixed, imho :)
