### ISSUE TITLE
WWX 2015 Speaker Profiles

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#106]
[Last](https://github.com/skial/haxe.io/issues/29) years speaker profiles thread.

cc @Merelleya

**Comment by Merelleya** [comment]
Yay,

I'm very happy to see this again. I will let you know as soon as anyone gets confirmed.

**Comment by Merelleya** [comment]
So here is the document where silex is maintaining their information. I will get back to them and ask them for the contact details, too.

https://docs.google.com/document/d/1AbUlLVRGG8_uVVVu_YPtOBr0Sux0hIM4P976u9Au3Io/edit#

**Comment by skial** [comment]
Thanks @Merelleya
