### ISSUE TITLE
Haxe Roundups 326 - 22.06.2015 - 28.06.2015

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#156]
To add to the roundup todo list, use the following markdown format.
```
- [ ] optional description [link name](/link/to/item) by [Persons Name](link/to/person)
```

**Comment by skial** [comment]
- [ ] HaxeFlixel Tutorial [Camera Zoom Revisited](https://twitter.com/laxa88/status/612468900614180865)
- [ ] Debugging the Haxe compiler with OcamlDebug [article](https://twitter.com/mandel59/status/612511077742448641)
- [ ] Andy Li is now working for Haxe Foundation! - [article](https://twitter.com/andy_li/status/613258994849677313)
- [ ] Haxe 3.2.0 chocolatey package now [live](https://twitter.com/andy_li/status/613611126043971584)
- [ ] Your next game with Haxe and HTML5 [article](https://twitter.com/thinkslow_fr/status/613715732682141696)
- [ ] [David](https://twitter.com/blackmagic_mt) from MotionTwin talking frameworks [pic](https://twitter.com/motiontwin/status/613734264023203840) at wgc2015
- [ ] Haxe + SDL = native love [gist](https://twitter.com/nadako/status/613793576011608064)
- [ ] Collow: Work in Progress [article](https://twitter.com/fierysquirrel/status/614022610008064000)
- [ ] NME still rocks [article](https://twitter.com/GameHaxe/status/614090806115241986)
- [ ] [Pic](https://twitter.com/leonanavi/status/614281816082546688) from Andy Li's talk
- [ ] [Slides](https://twitter.com/andy_li/status/614282063949262852) from Andy Li's talk
- [ ] TARDIS Go speed [improvements](https://twitter.com/TARDISgo/status/614351246091272192)

**Comment by skial** [comment]
- [ ] War of the Consoles : Haxe + OpenFL attack! [article](https://game2nextlevel.wordpress.com/2015/06/28/guerra-dos-consoles-haxe-openfl-ao-ataque/). Article written in Portuguese.
- [ ] Hello Haxe World [article](http://learnhaxe.org/haxe/hello-haxe-world/) from learnhaxe.org

**Comment by ProG4mr** [comment]
Hey, War of The Consoles article is written in Portuguese but its not from Portugal:

```
An article from Portugal, “Guerra dos Consoles: Haxe+OpenFL ao ataque!”,
```

The article is clearly (for someone familiar with it) written in Brazilian Portuguese, so it more likely comes from Brazil or someone who lives/lived in that country. Cheers.

**Comment by skial** [comment]
Thanks @ProG4mr, correction is on its way. :+1:
