### ISSUE TITLE
Ludum Dare 33 Roundup

### ISSUE THREAD

**Issue by Gama11** [skial/haxe.io#176]
@skial is a bit busy, so I decided to help out a bit by doing the LD33 roundup. I've started the a list on my fork, there's [65 games there so far](https://github.com/Gama11/haxe.io/blob/LudumDare33/src/ld/33.md).

If your game is not on there yet or doesn't link to your prefered social media handle, please post here using the usual format:

```
- [ ] [Game Name](link/to/ludum/dare/page) by [Your Name](link/to/social/site) using [Library Name](link/to/library).
```

Putting this list together is quite tedious (especially since there's some redundancy because of the markdown) and I'm sure I made a few mistakes here and here - please point it out if you find one. Also, a surprising number of people don't even mention the engine they used on the game page - oh well. I considered writing a tool that generates the list based on LD URL, social media URL and Engine... Even if that hadn't saved me much time, it would've been more fun at least. Next time maybe. :)

**Comment by dangerkun** [comment]
Hey thanks for having my game, I was to tired to write a proper description at the deadline but I said that I'm using haxeflixel in the blogpost thing, it's my first game with haxeflixel switching from as1 (yeah I know) and I like it a lot!

Thank you guys for your hard work, hope I can get good enough to contribute one day!

**Comment by deepnight** [comment]
[ ] [Delicious Cortext](http://ludumdare.com/compo/ludum-dare-33/?action=preview&uid=2982) by [deepnight](http://deepnight.net/) using only my own libs.

**Comment by PurpleApes** [comment]
- [ ] [I am not a monster](http://ludumdare.com/compo/ludum-dare-33/?action=preview&uid=39859) by [PurpleApes](http://www.purpleapes.com) using [Kha](https://github.com/KTXSoftware/Kha), [khage](https://github.com/wighawag/khage) and [cosmos](https://github.com/wighawag/cosmos).

**Comment by skial** [comment]
Thanks @Gama11 for doing this, I really appreciate it.

> I considered writing a tool that generates the list based on LD URL, social media URL and Engine... Even if that hadn't saved me much time, it would've been more fun at least. Next time maybe. :)

I thought exactly this _**every**_ single time...

@dangerkun Anything you create, let me know and I'll add it to the next roundup ;)

**Comment by anissen** [comment]
- [ ] [Monster's Ball](http://ludumdare.com/compo/ludum-dare-33/?action=preview&uid=30512) by [Anders Nissen](https://twitter.com/andershnissen) using [Luxe](http://luxeengine.com/docs/).

**Comment by johnhattan** [comment]
Kraken Babies. It's pretty much orthodox OpenFL, apart from Actuate (because it's awesome) and StableXUI (because I don't like coding buttons).

http://ludumdare.com/compo/ludum-dare-33/?action=preview&uid=56862

**Comment by TBaudon** [comment]
- [ ] [Rent-a-monster](http://ludumdare.com/compo/ludum-dare-33/?action=preview&uid=46262) by [@Damrem](https://twitter.com/damrem) and [@TBaudon](https://twitter.com/thomas_baudon) using [OpenFL](https://github.com/openfl/).

**Comment by scriptorum** [comment]
Very nice! Am I too late?

[Flappy Monster](http://ludumdare.com/compo/ludum-dare-33/?action=preview&uid=17811) by [@scriptorum](https://twitter.com/scriptorum) using [HaxePunk](http://www.haxepunk.com) and [Flaxen](http://www.github.com/scriptorum/flaxen).

**Comment by ryan0788** [comment]
- [ ] [Monster Frogger](http://ludumdare.com/compo/ludum-dare-33/?action=preview&uid=18263) by [Ryan Rossiter](http://ryanrossiter.com) using [HaxeFlixel](http://haxeflixel.com/).

**Comment by skial** [comment]
@scriptorum It's never to late :wink:

**Comment by skial** [comment]
@scriptorum and @ryan0788, yours game are now on the list.

Thanks **everyone** who submitted their LD games to the list :clap:
