### ISSUE TITLE
Dan's WWX interview answers

### ISSUE THREAD

**Issue by nadako** [skial/haxe.io#278]
[_template]: ../../templates/interview.html

## Tell us about yourself?

> 1. _How did you get started in programming?_

My parents brought me a ZX Spectrum clone with 48K RAM and BASIC for my 7th b-day. I've been programming since then.

> 1. _What is your job?_

I work in a game dev company called Plamee and we make mobile games. I was able to push Haxe there and is using it very successfully for the game logic part.

> ## Out of the various Haxe IDE's available, which one(s) do you use?

I was using Sublime Text for a long time, because I loved its simplicity and speed, however now I'm moving to VS Code, as it provides some great productivity features. Me and Simon are currently working on improving support for those in Haxe.

> ## What other software do you find vital while working with Haxe?

Github and Travis CI are really great for my open-source work.

> ## What hardware you do you use?

I'm mostly using a Windows PC, but I also have a macbook (tho I don't like OSX, so I have Windows there too). At my job, I sometimes have to deal with Android and iOS devices since we're developing games for them.

> ## What problem does Haxe solve for you?

For my job, main reason to use Haxe it its cross-platform abilities, of course. In general, I really appreciate Haxe's powerful type system and configurable compile-time behaviour through macros that allows me to write concise code and have small and efficient output, while still being safe.

Another great thing about Haxe is surely the community. Both devs and users are very smart, friendly and helpful, I really love to be a part of this.

> 3. _What ticks you off about Haxe, if anything? Lack of feature? Something else?_

I really miss null-safety and sometimes short-lambdas, but that's not critical and can be implemented to some extent.

> ## What compiler targets do you use?

For my work we use C# and JS. For the open-source stuff, I try to get things working on all haxe targets.

> ## What platforms to do deploy to?

Mobile (android and ios).

> ## What would you like to see added to the Haxe compiler?

Speaking of language features I'd appreciate null-safety, short-lambdas and tuples/destructuring.
But the most needed thing right now IMO is more IDE support features.

> ## What tips or resources would you recommend to a new Haxe user?

The new code cookbook resource by Mark Knol is really awesome (http://code.haxe.org/).
And of course one shouldn't forget good old manual, which is really well written IMO.

> ## What Haxe libraries and/or frameworks are you impressed by and use?

I don't use many libraries, but some really impress me, like Franco's Thx collection, Juraj's Tink libraries. Also, I really like the design of Rob's Kha framework and I'd love to use it someday.

> ## What is the best use of Haxe you've come across?

Can't really say what is the best use, but I'm really impressed to see cross-platform frameworks that leverages multiple haxe targets, especially new ones like Python.

> ## What do you think of the Haxe Foundation?

I'm not sure what the *foundation* really means, so to me it's just a group of core developers.

> 1. _Where have they excelled?_

Moving to GitHub was obvious, but nevertheless the best choice for Haxe, it brought so many contributors! Also, Andy Li's work on building and testing haxe and related products (haxelib, neko, etc) is one of the best things happened to Haxe.

> 2. _Areas you think they could improve?_

Maybe the communication within the team could be better. When I just joined the development, I was surprised that only so few developers are using the IRC channel.

> ## What contributions are you proud of?

I mostly contribute small fixes and polishing everywhere, as well as dev-version QA so I can only be proud of these as a whole. If everything goes well, I'll have a big reason to be proud of soon, but let's not talk about it for now. :)

Oh yeah, I forgout about `hxnodejs`, which seems to be greatly appreciated and used by people.

> 1. _Do you use them in your projects? Which?_

At work, we surely make use of the optimizations I done to the C# target.

> 2. _Did your contributions bring you work opportunities?_

Yeah, I'm getting mails from time to time. Once I even got an offer involving OCaml :-)

> ## Tell us about your WWX talk?

I want to make a short talk about how I managed to make my company use Haxe and how it worked out. This is going to be my first talk on public, and it's in foreign language, so I'm a bit nervous.

> ## What is the best part of WWX for you/are you looking forward too?

Metting like-minded people! \o/ Also visiting Paris :)

**Comment by skial** [comment]
Thanks @nadako for taking the time to answer and post your answers!

**Comment by skial** [comment]
Thanks again @nadako, its now [live](https://haxe.io/wwx/2016/Dan-Korostelev/), sorry it wasnt released sooner!
