### ISSUE TITLE
Rendering Issue in Chrome

### ISSUE THREAD

**Issue by bmfs** [skial/haxe.io#303]
OS: Windows 10 / Windows 7  (I've upgraded to 10 and the issue continued)
Browser: Chrome 
Browser Version: 50.0.2661.102 m

No logging in the console that could indicate the problem.

![haxe io](https://cloud.githubusercontent.com/assets/221471/15703122/ab004948-27db-11e6-8507-2bd25b659090.gif)

**Comment by ibilon** [comment]
Here's my network tab:
![haxeio](https://cloud.githubusercontent.com/assets/3843471/15703401/4e92cd7a-27e5-11e6-9fb5-1ae439155535.png)
is there any file that aren't loading in your chrome?

**Comment by skial** [comment]
Thanks @bmfs opening an issue, I'll start some testing, but I can tell thats the latest `frontpage.css` **not** rendering, but you appear to have the latest `index.html` and newest svg files. :confused:

**Comment by bmfs** [comment]
Network seems ok:
![haxe io network](https://cloud.githubusercontent.com/assets/221471/15704618/69368a4c-27e3-11e6-95cd-10f7d576f080.png)

Notice that it renders the page almost correct at some point, and then if breaks.

I have chrome update pending.
 Do you want me to update chrome to see if the problem goes away?

**Comment by skial** [comment]
> Notice that it renders the page almost correct at some point, and then if breaks.

I completely missed that. Makes it even more confusing now.

> I have chrome update pending.
Do you want me to update chrome to see if the problem goes away?

Only update if you normally would.

I see you have some chrome extensions enabled, could you, _whenever you have a spare moment,_ disable them to make sure they are not interfering, somehow!

**Comment by bmfs** [comment]
Good catch.
Found the culprit: "Grammarly for Chrome"

Will close the ticket now.

**Comment by skial** [comment]
> Found the culprit: "Grammarly for Chrome"

Thats weird.

I'll install it to see if I can figure it out.

Thanks again @bmfs.

**Comment by skial** [comment]
Ok, think I figured it out, I add to my `<html>` elements, in the case of `index.html` `class="\"`, generally the path, but could be template name. Anyway, the extension replaces this class completely, breaking rendering.

**Comment by skial** [comment]
It actually modifies the class attribute, not replaces it, so it's my css that's wrong.

**Comment by skial** [comment]
Fixed by 180d3d9780083fe01428421df09391bd8eeee7c6

**Comment by skial** [comment]
@bmfs you might have to clear your cache, but the cdns are now serving an updated `index.html` and `frontpage.css` that should stop interfering with Grammarly installed.

**Comment by bmfs** [comment]
@skial  Yeap, it works. Thanks
