### ISSUE TITLE
Ludum Dare 36 Roundup

### ISSUE THREAD

**Issue by Joffcom** [skial/haxe.io#334]
Are we following the same format as before?

`- [ ] [Game Name](link/to/ludum/dare/page), [compo or jam] entry by [Your Name](link/to/social/or/personal/site)
      using [Library Name](link/to/library). [Screen shot](link/to/picture).`

If we are... My entry is below :smile: 
- [x] [Nameless](http://ludumdare.com/compo/ludum-dare-36/?action=preview&uid=10348), [jam] entry by [Joff](https://twitter.com/joffcom)
    using [HaxeFlixel](http://haxeflixel.com/). [Screen shot](http://ludumdare.com/compo/wp-content/compo2//570486/10348-shot1-1472412316.png-eq-900-500.jpg).

**Comment by skial** [comment]
You know what, this LD completely passed me by, but yes, let's do it :+1:

**Comment by jeremyfa** [comment]
:)

- [ ] [The Machine](http://ludumdare.com/compo/ludum-dare-36/?action=preview&uid=50305), [jam] entry by [Jeremy Faivre](http://jeremyfa.com) using [pixi (haxe)](https://github.com/pixijs/pixi-haxe) & custom framework. [Screen shot](http://ludumdare.com/compo/wp-content/compo2//570486/50305-shot0-1472513039.png-eq-900-500.jpg).

**Comment by sebbernery** [comment]
- [ ] [Steam Train Youpi](http://ludumdare.com/compo/ludum-dare-36/?action=preview&uid=484), [compo] entry by [Sébastien Bernery](https://twitter.com/sebbernery) using [HaxeFlixel](http://haxeflixel.com/). [Screen shot](http://ludumdare.com/compo/wp-content/compo2/570486/484-shot0-1472422850.png).

**Comment by azlen** [comment]
- [ ] [Baba Yaga](http://ludumdare.com/compo/ludum-dare-36/?action=preview&uid=18078), [compo or jam] entry by [Azlen](https://azlen.github.io/) using [HaxeFlixel](http://haxeflixel.com/). [Screen shot](http://ludumdare.com/compo/wp-content/compo2//570486/18078-shot1-1472431984.png-eq-900-500.jpg).

**Comment by RudenkoArts** [comment]
- [ ] [Four](http://ludumdare.com/compo/ludum-dare-36/?action=preview&uid=47736), [compo] entry by [Rudenko](https://twitter.com/AndreiRudenko) using [Luxe](http://luxeengine.com/). [Screen shot](http://ludumdare.com/compo/wp-content/compo2//570486/47736-shot0-1472436408.png-eq-900-500.jpg).

**Comment by lightsoda** [comment]
- [ ] [Spear the sun](http://ludumdare.com/compo/ludum-dare-36/?action=preview&uid=19698), [compo] entry by [lightsoda](http://twitter.com/lightsoda) using [HaxeFlixel](http://haxeflixel.com/). [Screen shot](http://ludumdare.com/compo/wp-content/compo2//570486/19698-shot1-1472387758.png-eq-900-500.jpg).

**Comment by skial** [comment]
Thanks everyone who submitted their games :+1: 

You can see the current list of games at https://haxe.io/ld/36/, this list is built by scraping ludumdare, generating [`ld36.json`](https://github.com/skial/haxe.io/blob/d3b82ee41b1049bbd494650f603dcb24b74260fb/src/data/ld36.json) and a manually collected list [`ld36.manual.json`](https://github.com/skial/haxe.io/blob/d3b82ee41b1049bbd494650f603dcb24b74260fb/src/data/ld36.manual.json) for the two games that didnt have the few keywords I'm searching for. 

If your entry isnt on the list, either update your entry with the frameworks you used, leave a comment with a link to the game, or submit a pull request against the [`ld36.manual.json`](https://github.com/skial/haxe.io/blob/d3b82ee41b1049bbd494650f603dcb24b74260fb/src/data/ld36.manual.json).

Lets hope the next ld roundup doesn't take weeks to publish :smile:

**Comment by skial** [comment]
Thanks @starry-abyss for submitting your entry, it should be live in 15mins.
