### ISSUE TITLE
Interaction Developer (Toronto)

### ISSUE THREAD

**Issue by CharlesAnifowose** [skial/haxe.io#343]
http://ca.indeed.com/viewjob?t=interactions+developer&jk=d9bd4949ec8f1dfd&_ga=1.70502416.1421610120.1476279526

Our high-growth educational technology company requires a Interactions Developer to work on multi-departmental projects creating solutions that meet market needs relating to implementation, testing and maintenance. The Interactions Developer will be responsible for designing fully functioning, debugged code with required documentation that meets development goals.

**Job Duties**
- Create code, and test major features in collaboration with Team Members, Design Engineers, and other members of the development and technical team to deliver projects.
- Use existing code components to implement into new projects
- Maintain and modify existing applications.
- Perform custom programming as assigned.
- Debug and test software implementation.
- Interact with key partners and internal users regarding timelines, technical issues, and infrastructure integration.
- Provide recommendations for improvements in the overall development process.
- Ensure work progress to schedule and keep (internal) customers informed of project the progress.
- Stay current with trends, techniques, technology and other factors impacting the job.
- Actively participate in team meetings and offer recommendations /ideas on design projects.

**Requirements**
- Knowledge of AS3 and Haxe will will be a bonus.
- Able to effectively communicate technical concepts to other technical staff members.
- Able to effectively communicate with non-technical members of the organization.
- Demonstrated aptitude for learning new technologies.
- Effective written and verbal communication skills as well as presentation skills.
- Excellent teamwork and team building skills.
- Able to work well under pressure and meet set deadlines.
- Superior time management skills, multitasking skills, and the ability to prioritize tasks with minimal supervision.

Ability to follow through and complete overlapping projects.
High level of critical and logical thinking, analysis, and/or reasoning to identify underlying principles, reasons, or facts.

Experience with following is considered to be an asset 
- Haxe or Actionscript 3
- Git
- MySQL

_ABOUT VRETTA_
We are a rapidly expanding research and design company that is using technology to transform the way we learn and use math every day. We collaborate with schools, colleges, governments, and NGOs around the world to re-imagine what really matters for students in the 21st century and to make sure that every student acquires meaningful quantitative skills that will serve them in their lives and professions.

The user experience is at the heart of our creative process. This experience determines what sticks and what fades, and we see this as a tremendous opportunity to do better than anyone that has come before us. Every project is assigned a highly focused team of researchers, educators, designers, and software developers that are passionate about making an impact.

**Comment by CharlesAnifowose** [comment]
sorry for the repost @skial , I thought this would be easier

**Comment by skial** [comment]
Thanks @CharlesAnifowose thats brilliant, thanks for posting more information about the job.

> sorry for the repost @skial , I thought this would be easier

No problem at all.
