### ISSUE TITLE
Haxe/flash developer (Minsk, Belarus)

### ISSUE THREAD

**Issue by Beeblerox** [skial/haxe.io#349]
Playtika (https://playtika.com/) is looking for a Haxe developer in Minsk office (Belarus).
Here is the link to source tweet (it's in Russian): https://twitter.com/ryzzed/status/786251640810635264
If you interested then you can contact with Katya Lusto (https://twitter.com/lihamanka) who is responsible for recruiting.

**Comment by skial** [comment]
Thanks @Beeblerox, its now in roundup 371.
