### ISSUE TITLE
Need someone finishing a a port

### ISSUE THREAD

**Issue by aidinzolghadr** [skial/haxe.io#361]
Hi,

Someone has helped us port a game of mine, Rot Gut (http://store.steampowered.com/app/395500?beta=0) to HaxeFlixel but despite the port being %95 done (As he claims), he unfortunetly could not finish it and optimize the game to run smoothly on iOS devices.

I need someone with good experience of HaxeFlixel to help finishing the port. If you are interested, please let me know.

Thanks.

(I've been told I can post job listing here, if not, I'm sorry to interrupt)

**Comment by skial** [comment]
Hey @aidinzolghadr I was on hiatus for afew months, so this probably didnt get any attention, sorry. 

If you're still looking for someone let me know and I'll include it in the next roundup, etc.
