### ISSUE TITLE
Haxe (London, UK) job offer

### ISSUE THREAD

**Issue by mimingng** [skial/haxe.io#378]
We are looking for an experienced Haxe developer to help us with the enhancement of an existing skill game. We are based in London, UK and the candidate should be / willing to move to London for this project (around 3 months). The ideal candidate should have good experience working with the OpenFL framework, for building web games.

We use the following third-party tools: actuate, box2 and lime.
Knowledge in using git is essential.

About us
rocabee is a gaming enthusiasts and trusted provider in the online gaming industry based in London, building skill games and educational services for web/mobile. We are a member of The UK Interactive Entertainment Association (Ukie).

The game you'll be working on is a traditional Turkish board game played by all generations, created for web and mobile app. It is already live in Iran, but we need to adjust it now for other markets with new features - single-player and monetisation. 

I'd be more than happy to answer all further questions - feel free to contact me on mimi@rocabee.com

**Comment by skial** [comment]
Thanks @mimingng for posting the job, can you provide some contact details/instructions for people who might be interested.

**Comment by mimingng** [comment]
@skial thanks for your help!
I've edited the post with some more info:)

**Comment by skial** [comment]
@mimingng Thank you :+1:

**Comment by skial** [comment]
Hi @mimingng, has this job been filled yet?
