### ISSUE TITLE
robotlegs macrobot link

### ISSUE THREAD

**Issue by mayakwd** [skial/haxe.io#387]
Hello, in the latest round up link for macrobot is forwarding to git, but library is released on haxelib:
https://lib.haxe.org/p/robotlegs-macrobot/

**Comment by skial** [comment]
Thanks @mayakwd for pointing that out, I didn't notice it was on haxelib.

**Comment by skial** [comment]
The update should be live in ~15mins.

**Comment by mayakwd** [comment]
@skial, thank you!
