### ISSUE TITLE
Looking for OpenFL/Haxe/HTML5 developers

### ISSUE THREAD

**Issue by otisurdoden** [skial/haxe.io#392]
FIXED TERMS/FREELANCE (6 months)

We are currently looking for several programmers with intermediate or advanced experience in Javascript HTML5 game development for short term porting missions (bringing flash games to native html5 using a conversion tool and existing libraries, the main job lies in debugging and optimizing). Fishing Cactus has developed a very unique skillset and expertise in porting Flash games to HTML5 for the past years. We are looking to strengthen our team with new profiles.

REQUIREMENTS
- Computer science degree or equivalent experience
- JavaScript development (including debugging and optimizing)
- Knowledge of WebGL and Canvas API
- Experience with at least a version control system such as Git
- OpenFL, ActionScript 2/3 and/or Haxe knowledge or experience is a huge plus
- 1+ year in game development or equivalent game development degree is a plus
- You can read and write in English on a daily basis

Full job posting: http://emploi.afjv.com/emploi-jeux-video/EDEV610-11668

**Comment by skial** [comment]
Thanks @otisurdoden I've updated the latest roundup with a link to the full job post. 

Let me know when all positions are filled :+1:

**Comment by otisurdoden** [comment]
Thanks! Much appreciated!

**Comment by skial** [comment]
@otisurdoden has this been filled?
