### ISSUE TITLE
Haxe/OpenFL Game Developer – Forge of Empires

### ISSUE THREAD

**Issue by Forgegamer** [skial/haxe.io#414]
As a **Haxe/OpenFL Game Developer** you will be part of our agile, cross-functional and international development team. You will drive the development of new features on client-side as well as maintain and improve the current code of our most successful game. You will start working on our HTML5 browser client based on Haxe/OpenFL. You will improve existing and start developing new features. Bring your knowledge of code quality and software engineering principles to provide the best user experience for our players.

**Your mission:**
•	Develop new and improve existing game-features in Haxe/OpenFL
•	Working in close collaboration with Backend Developers, Game Design and QA
•	Ensure high quality of our source code through reviews, unit-tests and usage of clean code
•	Actively contribute to the whole feature development lifecycle

**Your profile:** 
•	Several years of relevant professional experience, ideally in game development
•	Passionate developer with profound knowledge in object-oriented programming
•	Solid experience in Unit Testing, Design Patterns, Code-Reviews
•	Familiar with agile methodologies like Scrum and Kanban
•	Team player and good communicator with fluent English language skills

**Why join us?** 
•	Shape the success story of InnoGames with a great team of driven experts in an international culture
•	Competitive compensation and an atmosphere to empower creative thinking and strong results
•	Exceptional benefits ranging from flawless relocation support to company gym, smartphone or tablet of your own choice for personal use, roof terrace with BBQ and much more

Would you like to become part of a dynamic team and work as a Haxe/ OpenFL Game Developer in our new mobile game. Then we look forward to receiving your application (cover letter, CV and references) as well as your salary expectations and earliest possible starting date through our [online application form](https://www.innogames.com/career/detail/job/haxe-openfl-game-developer-forge-of-empires?s=haxe_io_roundup) at innogames.com. Your contact person for this job offer is **Cagla Toksoy**.

InnoGames, based in Hamburg, is one of the leading developers and publishers of online games with more than 150 million registered players around the world. Currently, more than 400 people from 30 nations are working in Hamburg and Düsseldorf. We have been characterized by dynamic growth ever since the company was founded in 2007. In order to further expand our success and to realize new projects, we are constantly looking for young talents, experienced professionals, and creative thinkers.

**Comment by nadako** [comment]
@Forgegamer Interesting stuff! Do you by any chance know if Inno Games people are going to attend this year's Haxe Summit in Amsterdam?

**Comment by Forgegamer** [comment]
@nadako Yes, the whole Haxe team of Forge of Empires is going to attend
