### ISSUE TITLE
Suggestion: Make links open in new tab by default -- target=_blank

### ISSUE THREAD

**Issue by jcward** [skial/haxe.io#435]
Hi Brendon,

Every time I look through theses excellent round-ups, I forget to ctrl-click the links, so that when I want to get back and browse more, I have to click back (often multiple times, or usually I forget and close the tab, then have to reopen AND click back). Perhaps it's just me, but I feel like content aggregations (big pages of links) typically open links in new tabs by default, and I kind of like that.

This may be a desktop bias, but I think it's the same on mobile (I browse on mobile less frequently.)

Maybe others could weigh in -- **opening links in a new tab by default: irritating or nice feature?** Maybe here, maybe a twitter poll?

Just a thought. Regardless, thanks for your hard work!!

Best,
-Jeff

**Comment by skial** [comment]
No, thats a fair point to make, typically links to external sites are `target=_blank`. The behaviour, I'm pretty sure, is the same for mobile.

**Comment by kevinresol** [comment]
> irritating or nice feature

irritating.
if default is _self: for those who want to open in new window/tab -> just ctrl-click it = easy.
if default is _blank: for those who want to open in current window/tab -> how to?

**Comment by skial** [comment]
I'm going to test it on the next roundup and see if their is any reaction to the change.

**Comment by jcward** [comment]
Cool - let us know if you have any reaction. I love it (on desktop), because I'm used to browsing Twitter which does this by default. But I guess it depends on what people are used to.

I tried it on mobile (Android), and it's basically the same with or without, because the android back button "goes back" regardless of whether it was a new tab. I'm not sure what iOS does.

Popular content aggregators seem split -- social networks like Twitter, FB, imgur, and tumblr do open external links in new tabs. While sites like Reddit and hacker news don't.

But, it's only your audience that matters to you, so we'll see if anybody notices.

**Comment by skial** [comment]
Nobody has said anything about the change so it will stay for now :+1:
