### ISSUE TITLE
Mark entries as "ONGOING" if already appeared in previous roundups

### ISSUE THREAD

**Issue by kevinresol** [skial/haxe.io#565]
I think this will help readers who follow the roundups closely, so they can quickly spot out what is new.

**Comment by skial** [comment]
I'm guessing you mean a sub section like?

```md
## Community Updates

### News and Articles

- latest article from [twitter](https://twitter.com/)

#### Ongoing

- last weeks links
```

Maybe _"In case you missed it"_ as the heading might be more appropriate?

**Comment by kevinresol** [comment]
Initially I thought it is just a little tag at the beginning a of an item. But your idea sounds great too.
