### ISSUE TITLE
It is not clear that "In case you missed it" text is clickable (in Firefox)

### ISSUE THREAD

**Issue by Beeblerox** [skial/haxe.io#652]
I see that you've added new feature to roundups: "In case you missed it" section are now foldable/unfoldable. But it is not clear (at least to me) that you could click on the text, so my initial thought was that you forgot to add text for these sections (and i even wanted to correct roundup issue). And only by accident i've clicked on "In case you missed it" text :)
So i think that it should be visually different to make it clear that you could unfold these sections

**Comment by Beeblerox** [comment]
@skial you can see this issue only in Firefox. Chrome and IE are fine

**Comment by skial** [comment]
I just realised the browsers default style is being overridden in css and firefox seems to be the only one to respect that.

**Comment by Beeblerox** [comment]
Works fine now!
