### ISSUE TITLE
Asking for voluntary help for a haxe MMORPG !

### ISSUE THREAD

**Issue by zekrosem** [skial/haxe.io#656]
Hello my friends, 

I am currently building a whole mmorpg project inspired by a closed game : Pet Forest Online with little to major improvements ! I've been working alone for the past few weeks, but now that I'm starting to have a strong basis for the game components, I'm also starting to reach the limits of what's possible to do without content, and especially without further help ! 

If you'd like to join the team (aka me) and bring your happiness, motivation, skills (gfx, level design, game design, community management, marketing,...), feel free to contact me on Haxe discord : @Ze (phil)#4538 or on twitter @zekrosem !

Oh, almost forgot, as you may guess, I can only pay you with cookies and candies... Thank you !

**Comment by skial** [comment]
Thanks for asking here @zekrosem. You might get better visibility asking over on https://community.haxe.org/ though.
