### ISSUE TITLE
Typo in "Submit" a Link

### ISSUE THREAD

**Issue by bsinky** [skial/haxe.io#680]
Noticed this typo in the "Submit a Link" button, it reads "Sumbit a Link" instead. I'd open a PR to fix, but I haven't been able to find the error in the repo? 😕 

![image](https://user-images.githubusercontent.com/5004786/66573249-fc4acd00-eb37-11e9-9a2e-b9e0bf037047.png)

**Comment by skial** [comment]
Thanks for reporting @bsinky I've fixed the source, the templates are in a branch I've not pushed yet.
