### ISSUE TITLE
Haxe Round 588

### ISSUE THREAD

**Issue by skial** [skial/haxe.io#891]
To add to the roundup todo list, use the following markdown format.

```
- [ ] optional description [link name](/link/to/item)
```
So it generates the following:

- [x] optional description [link name](/link/to/item)

**Comment by skial** [comment]
- [ ] `[community]` StoryDev - A parser for interactive story development now has its [own editor](https://community.haxe.org/t/storydev-a-parser-for-interactive-story-development/966/2?u=skial).

**Comment by skial** [comment]
- [ ] `[core]` @:multiType-inception instantiates non-existent constructors [issue](https://github.com/HaxeFoundation/haxe/issues/10318).

**Comment by skial** [comment]
- [ ] libs
  - [spine-hx `4.0.2`](https://lib.haxe.org/p/spine-hx)
  - [hxneu `1.0.0`](https://lib.haxe.org/p/hxneu)
  - [grig.midi `0.0.7`](https://lib.haxe.org/p/grig.midi)
  - [coroutine `2.0.1`](https://lib.haxe.org/p/coroutine)

**Comment by skial** [comment]
- [ ] `[community/pateron locked]` :closed_lock_with_key: One-Way Collisions [article](https://www.ohsat.com/tutorial/flixel/one-way-collisions/index.php) by [Andrej](https://twitter.com/ohsat_games).

**Comment by skial** [comment]
- [ ] `[videos]` Introduction to HaxeFlixel [Part 20](https://www.youtube.com/watch?v=QTqM8Fy2ha4&widget_referrer=haxe.io) by Questionable Programming.

**Comment by skial** [comment]
- [ ] `[videos]` Why does Awesome HaxeFlixel exist? HaxeFlixel game development resources [video](https://www.youtube.com/watch?v=f2QS55Zk42A&widget_referrer=haxe.io) by Richard Oliver Bray.

**Comment by skial** [comment]
- [ ] `[open source]` [HxRT `git`](https://github.com/Vurv78/HxRT) - Raytracer in Haxe.

**Comment by skial** [comment]
- [ ] `[open source]` [webidl-haxe `git`](https://github.com/Apprentice-Alchemist/webidl-haxe)

**Comment by skial** [comment]
- [ ] `[videos]` ArmorPaint. News. July 21, 2021 [video](https://www.youtube.com/watch?v=DwIY8lfSy2c&widget_referrer=haxe.io) by [Alexander Kiryanov](https://twitter.com/AlexandrKiryan3/status/1417839213505044480).

**Comment by skial** [comment]
- [ ] `[closed source]` The fall season in GoGoPogoGirl is full of mushrooms that are just as bouncy as PogoGirl herself by [Andrej](https://twitter.com/ohsat_games/status/1417546345997537287). :mushroom:

**Comment by skial** [comment]
- [ ] `[closed source]` The end is in sight for Bad Soccer Manager by [Jano Games](https://twitter.com/jano_games/status/1417416429788450826), within the next two weeks. Check out the Crossbar challenge, the newest mini game. Available on [`itch.io/bad-soccer-manager`](https://janogames.itch.io/bad-soccer-manager). Made in Stencyl.

**Comment by skial** [comment]
- [ ] `[closed source]` Super Cosmic Heist `2022` The Horizon Towers Level Two `WIP` by [Fierce](https://twitter.com/FierceTheBandit/status/1417223548440129536). Made in Stencyl.

**Comment by skial** [comment]
- [ ] `[releases]` [Dan Hett](https://twitter.com/danhett/status/1417139706396037132) is getting ready to put a paid version of Closed Hands up on Steam, with loads of extra content, soundtrack and a directors commentary, plus lots more.

**Comment by skial** [comment]
- [ ] `[closed source]` A preview of ArmorPaint on iPad with cloud support by [Lubos Lenco](https://twitter.com/luboslenco/status/1417077252584509441).

**Comment by skial** [comment]
- [ ] `[closed source]` Slow motion makes everything _cooler_ by [Ty](https://twitter.com/zzo__x/status/1416452520042450944).

**Comment by skial** [comment]
- [ ] `[releases]` Check out the [Colorful 3D Platformer Bundle](https://store.steampowered.com/bundle/21862/Colorful_3D_Platformer_Bundle/) on Steam featuring the Haxe powered Speebot game by [Keyreal](https://twitter.com/keyreal/) via [Allan Dowdeswell](https://twitter.com/confidant_ca/status/1416082618471395330).

**Comment by skial** [comment]
- [ ] `[videos/audio]` Episode 57 "The Future of Web Games" of The Newgrounds Podcast :ng: featuring Lars Doucet, Nicolas Cannasse and Cameron _(ninja_muffin99)_ is now available! via [Lars Doucet](https://twitter.com/larsiusprime/status/1416045625658036224).

**Comment by Beeblerox** [comment]
- [ ] [Teleporting uses energy](https://twitter.com/Rob1221dev/status/1416049927042514948) in WIP game by Robert Alvarez

**Comment by Beeblerox** [comment]
- [ ] [Temp interiors. A witch's home](https://twitter.com/RobClemmonsJr/status/1416283872346656772) from WIP game [Patches Of Adventure](https://claybrickentertainment.itch.io/patches-of-adventure)

**Comment by Beeblerox** [comment]
- [ ] [New stage unlocked!](https://twitter.com/mauvecow/status/1416613606611849223) animation from WIP game Addlemoth by mauve

**Comment by Beeblerox** [comment]
- [ ] [New puzzle mechanic - Devlog 4](https://www.youtube.com/watch?v=-Y8Y886k9pc) video by [Kirill Poletaev](https://twitter.com/kircode/status/1416774447525244928)
- [ ] And [new screenshots](https://twitter.com/kircode/status/1416454109910142979) from the second world of Pilie Pals

**Comment by Beeblerox** [comment]
- [ ] [ArmorPaint on iPadOS](https://twitter.com/luboslenco/status/1417077252584509441) with cloud support. Coming to the AppStore!

**Comment by Beeblerox** [comment]
- [ ] [Techy Wrinkles](https://twitter.com/techywrinkles/status/1415879221126344705) got the placeholder baddies shooting + going for an R-Type level of enemy diversity with a home console shmup level of difficulty

**Comment by Beeblerox** [comment]
- [ ] [Haxe externs](https://github.com/Orange-hx/hxneu) for Neutralino.js by Rabia Alhaffar

**Comment by Beeblerox** [comment]
> * [ ]  `[open source]` [webidl-haxe `git`](https://github.com/Apprentice-Alchemist/webidl-haxe)

- [ ] by [Zeta](https://discord.com/channels/162395145352904705/162664383082790912/866327854815641680). It is a WIP webidl parser, which also includes a small extern generator. Right now it can parse the WebGPU spec, and part of the DOM spec.

**Comment by Beeblerox** [comment]
- [ ] `[showcase]` [Poker Quest - a poker themed roguelike](https://community.openfl.org/t/poker-quest-a-poker-themed-roguelike/13131)

**Comment by skial** [comment]
- [ ] `[open source]` [boxup.compiler `git`](https://github.com/wartman/boxup.compiler) - Simple, structured markup.

**Comment by skial** [comment]
- [ ] `[releases]` [Shiro Games](https://twitter.com/shirogames/status/1417483200037801987) have published Northgard [Balancing Patch `#7` ~ July 2021](https://steamcommunity.com/games/466560/announcements/detail/5016431176761421494) release notes.

**Comment by skial** [comment]
- [ ] `[open source/haxe discord]` [Ben Van Treese](9https://discord.com/channels/162395145352904705/162664383082790912/865354021686214716) has updated their language generator  to have links to pronunciations, plus some style cleanup. Check out the [live demo](https://dropecho.github.io/langgen/?seed=55372801373).
